### ISSUE TITLE
your thoughts on broadcast

### ISSUE THREAD

**Issue by btsimonh** [WojciechMatuszewski/cdk-lambdaless-apigw-websockets#1]
We have an application, which for the moment 'connects' a group of users.  But we've use raw websockets because some of the data is raw 24 bit 2Mbit audio....  and so every ms counts, and every buffer conversion costs....
We also direct messages according to message content (some broadcast, some directed).

In your opinion, is there any way to implement this 'serverless' using the amazon APIs and achieve anything like the above?
I did consider running up a lambda every 10 mins, but lambda can't have incoming TCP!!!

So at the moment the only option is a dedicated EC2 each time we hit a capacity limit.

br,
Simon

**Comment by WojciechMatuszewski** [comment]
Hey @btsimonh 

If you have a broadcast use case, I would strongly recommend looking into [IoT Core MQTT](https://docs.aws.amazon.com/iot/latest/developerguide/topics.html) that power the [AppSync GraphQL subscriptions](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html) and are entirely serverless. To be completely honest, I would only use APIGW WebSockets for small, 1:1 connection model.

**Comment by WojciechMatuszewski** [comment]
A long time ago, I had [played around with IoT WebSockets](https://github.com/WojciechMatuszewski/iot-core-feature-flags). The repository is a bit of a mess, but maybe it will help you?

For production code, I would look into official AWS workshops, like [this one](https://catalog.us-east-1.prod.workshops.aws/workshops/6d30487a-48e1-4631-b6bc-5602582800b5/en-US/chapter4-mqttmessages/10-dc-setup).

Feel free to reach out if you have more questions.
